# Generated by Django 5.2.8 on 2025-12-18 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('finances', '0003_savingproducts_savingoptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('risk_tolerance', '위험감수성'), ('investment_experience', '투자경험'), ('financial_status', '재무상태'), ('investment_period', '투자기간'), ('investment_knowledge', '투자지식')], max_length=30)),
                ('question_text', models.TextField(help_text='질문 내용')),
                ('order', models.IntegerField(default=0, help_text='질문 순서')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'survey_question',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_type', models.CharField(blank=True, choices=[('very_conservative', '불안형'), ('conservative', '안정추구형'), ('moderate', '중립형'), ('aggressive', '적극투자형'), ('very_aggressive', '투기형')], max_length=20, null=True)),
                ('risk_score', models.IntegerField(default=0)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('income', models.DecimalField(blank=True, decimal_places=0, help_text='연 소득 (만원)', max_digits=12, null=True)),
                ('savings', models.DecimalField(blank=True, decimal_places=0, help_text='현재 저축액 (만원)', max_digits=12, null=True)),
                ('investment_goal', models.CharField(blank=True, help_text='예: 주택구매, 노후준비, 자녀교육 등', max_length=50, null=True)),
                ('investment_period', models.IntegerField(blank=True, help_text='투자 가능 기간 (개월)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investment_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '투자 성향 프로필',
                'verbose_name_plural': '투자 성향 프로필들',
                'db_table': 'investment_profile',
            },
        ),
        migrations.CreateModel(
            name='SurveyChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.TextField(help_text='선택지 내용')),
                ('score', models.IntegerField(help_text='점수 (1~5점, 높을수록 공격적)')),
                ('order', models.IntegerField(default=0, help_text='선택지 순서')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='accounts.surveyquestion')),
            ],
            options={
                'db_table': 'survey_choice',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(help_text='매칭 점수 (0~100)')),
                ('recommended_reason', models.TextField(help_text='추천 이유')),
                ('is_viewed', models.BooleanField(default=False)),
                ('is_bookmarked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.depositproducts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'product_recommendation',
                'ordering': ['-match_score', '-created_at'],
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.surveychoice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.surveyquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'survey_response',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'question')},
            },
        ),
    ]
