# Generated by Django 5.2.8 on 2025-12-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_surveyquestion_investmentprofile_surveychoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', '남성'), ('F', '여성')], help_text='성별', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='investmentprofile',
            name='risk_type',
            field=models.CharField(blank=True, choices=[('timid_male', '에겐소심남'), ('normal_male', '보통남'), ('speculative_male', '테토투기남'), ('timid_female', '에겐소심녀'), ('normal_female', '보통녀'), ('speculative_female', '테토투기녀')], max_length=20, null=True),
        ),
    ]
