# Generated by Django 5.2.8 on 2025-12-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_investmentprofile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentprofile',
            name='risk_type',
            field=models.CharField(blank=True, choices=[('timid_male', '에겐소심남'), ('normal_male', '중간남'), ('speculative_male', '테토투기남'), ('timid_female', '에겐소심녀'), ('normal_female', '중간녀'), ('speculative_female', '테토투기녀')], max_length=20, null=True),
        ),
    ]
