# Generated by Django 5.2.8 on 2025-12-20 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_savingproducts_savingoptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositoptions',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='finances.depositproducts'),
        ),
    ]
